account:
  username: your_username
  email_or_phone: your_email_or_phone
  password: your_password

browser:
  browser: edge # edge, chrome, firefox
  headless: true  
  user_agent: ""

bot:
  max_posts: 50        
  refresh_interval: 60.0  
  filter_tags: []
  trigger: like # like, bookmark
  autolike: true
  max_autolike_posts: 10
  autolike_users: []
  save_path: "./data"

